import { type CategoryKey, type CategoryType } from '../constants/categories';

export const mockTransactions = [
  {
    id: 'rent',
    title: 'Rent Payment',
    account: 'RBC Credit Card',
    note: "October's fee · Mr. L Lord",
    amount: -780,
    dateLabel: 'Yesterday',
    type: 'expense' as CategoryType,
    icon: 'home-city-outline',
    categoryId: 'housing' as CategoryKey,
    subcategoryId: 'housing:rent',
  },
  {
    id: 'salary',
    title: 'Salary',
    account: 'RBC Account',
    note: "September's · Company X",
    amount: 4500,
    dateLabel: 'Oct 18, 2025',
    type: 'income' as CategoryType,
    icon: 'briefcase-outline',
    categoryId: 'income' as CategoryKey,
    subcategoryId: 'income:salary',
  },
  {
    id: 'fuel',
    title: 'Fuel',
    account: 'RBC Credit Card',
    note: 'Gas · Mobil',
    amount: -18.52,
    dateLabel: 'Oct 18, 2025',
    type: 'expense' as CategoryType,
    icon: 'gas-station-outline',
    categoryId: 'transportation' as CategoryKey,
    subcategoryId: 'transportation:fuel',
  },
  {
    id: 'groceries',
    title: 'Groceries (10)',
    account: 'RBC Credit Card',
    note: 'Milk (9) · Walmart',
    amount: -50.7,
    dateLabel: 'Oct 16, 2025',
    type: 'expense' as CategoryType,
    icon: 'cart-outline',
    categoryId: 'groceries' as CategoryKey,
    subcategoryId: 'groceries:supermarket',
  },
  {
    id: 'stationary',
    title: 'Stationery',
    account: 'RBC Credit Card',
    note: 'Notebooks · Staples',
    amount: -4.7,
    dateLabel: 'Oct 14, 2025',
    type: 'expense' as CategoryType,
    icon: 'pencil-outline',
    categoryId: 'groceries' as CategoryKey,
    subcategoryId: 'groceries:household',
  },
  {
    id: 'coffee',
    title: 'Coffee',
    account: 'Visa Infinite',
    note: 'Latte · Starbucks',
    amount: -5.99,
    dateLabel: 'Oct 12, 2025',
    type: 'expense' as CategoryType,
    icon: 'coffee-outline',
    categoryId: 'dining' as CategoryKey,
    subcategoryId: 'dining:coffee',
  },
  {
    id: 'movie',
    title: 'Movie Tickets',
    account: 'Amex Platinum',
    note: 'Avengers · Cineplex',
    amount: -25.0,
    dateLabel: 'Oct 10, 2025',
    type: 'expense' as CategoryType,
    icon: 'movie-open-outline',
    categoryId: 'entertainment' as CategoryKey,
    subcategoryId: 'entertainment:movies',
  },
  {
    id: 'freelance',
    title: 'Freelance Work',
    account: 'PayPal',
    note: 'Web design · Client Y',
    amount: 1200.0,
    dateLabel: 'Oct 08, 2025',
    type: 'income' as CategoryType,
    icon: 'laptop',
    categoryId: 'income' as CategoryKey,
    subcategoryId: 'income:freelance',
  },
  {
    id: 'gym',
    title: 'Gym Membership',
    account: 'Mastercard',
    note: 'Monthly fee · FitLife',
    amount: -49.99,
    dateLabel: 'Oct 06, 2025',
    type: 'expense' as CategoryType,
    icon: 'dumbbell',
    categoryId: 'health' as CategoryKey,
    subcategoryId: 'health:gym',
  },
  {
    id: 'internet',
    title: 'Internet Bill',
    account: 'RBC Account',
    note: 'Monthly · Bell',
    amount: -89.99,
    dateLabel: 'Oct 04, 2025',
    type: 'expense' as CategoryType,
    icon: 'wifi',
    categoryId: 'utilities' as CategoryKey,
    subcategoryId: 'utilities:internet',
  },
  {
    id: 'electricity',
    title: 'Electricity Bill',
    account: 'RBC Account',
    note: 'Monthly · Hydro One',
    amount: -120.5,
    dateLabel: 'Sep 30, 2025',
    type: 'expense' as CategoryType,
    icon: 'flash-outline',
    categoryId: 'utilities' as CategoryKey,
    subcategoryId: 'utilities:electricity',
  },
  {
    id: 'dinner',
    title: 'Dinner Out',
    account: 'Visa Infinite',
    note: 'Italian Restaurant · Downtown',
    amount: -75.2,
    dateLabel: 'Sep 28, 2025',
    type: 'expense' as CategoryType,
    icon: 'silverware-fork-knife',
    categoryId: 'dining' as CategoryKey,
    subcategoryId: 'dining:restaurant',
  },
  {
    id: 'bonus',
    title: 'Performance Bonus',
    account: 'RBC Account',
    note: 'Quarterly · Company X',
    amount: 2500.0,
    dateLabel: 'Sep 25, 2025',
    type: 'income' as CategoryType,
    icon: 'wallet-plus',
    categoryId: 'income' as CategoryKey,
    subcategoryId: 'income:bonus',
  },
  {
    id: 'shopping',
    title: 'Online Shopping',
    account: 'Amex Platinum',
    note: 'Clothes · Amazon',
    amount: -150.99,
    dateLabel: 'Sep 22, 2025',
    type: 'expense' as CategoryType,
    icon: 'shopping-outline',
    categoryId: 'groceries' as CategoryKey,
    subcategoryId: 'groceries:supermarket',
  },
  {
    id: 'gas',
    title: 'Gas Station',
    account: 'Mastercard',
    note: 'Fuel · Shell',
    amount: -45.3,
    dateLabel: 'Sep 20, 2025',
    type: 'expense' as CategoryType,
    icon: 'gas-station-outline',
    categoryId: 'transportation' as CategoryKey,
    subcategoryId: 'transportation:fuel',
  },
  {
    id: 'investment',
    title: 'Stock Dividend',
    account: 'Questrade',
    note: 'Monthly · Tech Corp',
    amount: 200.75,
    dateLabel: 'Sep 18, 2025',
    type: 'income' as CategoryType,
    icon: 'chart-line',
    categoryId: 'income' as CategoryKey,
    subcategoryId: 'income:investments',
  },
  {
    id: 'pharmacy',
    title: 'Pharmacy',
    account: 'Visa Infinite',
    note: 'Medicines · CVS',
    amount: -32.45,
    dateLabel: 'Sep 15, 2025',
    type: 'expense' as CategoryType,
    icon: 'medical-bag',
    categoryId: 'health' as CategoryKey,
    subcategoryId: 'health:pharmacy',
  },
  {
    id: 'concert',
    title: 'Concert Tickets',
    account: 'Amex Platinum',
    note: 'Jazz Night · Local Venue',
    amount: -85,
    dateLabel: 'Sep 12, 2025',
    type: 'expense' as CategoryType,
    icon: 'music-circle-outline',
    categoryId: 'entertainment' as CategoryKey,
    subcategoryId: 'entertainment:concerts',
  },
  {
    id: 'freelance2',
    title: 'Freelance Project',
    account: 'PayPal',
    note: 'App Development · Client Z',
    amount: 1800.0,
    dateLabel: 'Sep 10, 2025',
    type: 'income' as CategoryType,
    icon: 'laptop',
    categoryId: 'income' as CategoryKey,
    subcategoryId: 'income:freelance',
  },
  {
    id: 'insurance',
    title: 'Car Insurance',
    account: 'RBC Account',
    note: 'Annual · Insurance Co',
    amount: -350,
    dateLabel: 'Sep 08, 2025',
    type: 'expense' as CategoryType,
    icon: 'shield-check-outline',
    categoryId: 'insurance' as CategoryKey,
    subcategoryId: 'insurance:auto',
  },
  {
    id: 'lunch',
    title: 'Lunch',
    account: 'Visa Infinite',
    note: 'Sandwich · Subway',
    amount: -12.99,
    dateLabel: 'Sep 05, 2025',
    type: 'expense' as CategoryType,
    icon: 'food-outline',
    categoryId: 'dining' as CategoryKey,
    subcategoryId: 'dining:fast',
  },
];

export const mockRecordsData = [
  { id: 'rent', title: 'Rent Payment', subtitle: 'Housing - Rent', account: 'RBC Credit Card', amount: -780, dateLabel: 'Yesterday', type: 'expense' as CategoryType, date: new Date(2025, 9, 23), categoryId: 'housing' as CategoryKey, subcategoryId: 'housing:rent' },
  { id: 'salary', title: 'Monthly Salary', subtitle: 'Income - Salary', account: 'RBC Account', amount: 4500, dateLabel: 'Oct 01', type: 'income' as CategoryType, date: new Date(2025, 9, 1), categoryId: 'income' as CategoryKey, subcategoryId: 'income:salary' },
  { id: 'fuel', title: 'Fuel Refill', subtitle: 'Transportation - Fuel', account: 'Mastercard', amount: -95.5, dateLabel: 'Sep 30', type: 'expense' as CategoryType, date: new Date(2025, 8, 30), categoryId: 'transportation' as CategoryKey, subcategoryId: 'transportation:fuel' },
  { id: 'groceries', title: 'Metro Groceries', subtitle: 'Groceries - Supermarket', account: 'Metro Market', amount: -210.99, dateLabel: 'Sep 29', type: 'expense' as CategoryType, date: new Date(2025, 8, 29), categoryId: 'groceries' as CategoryKey, subcategoryId: 'groceries:supermarket' },
  { id: 'bonus', title: 'Quarterly Bonus', subtitle: 'Income - Bonus', account: 'RBC Account', amount: 1250.25, dateLabel: 'Sep 27', type: 'income' as CategoryType, date: new Date(2025, 8, 27), categoryId: 'income' as CategoryKey, subcategoryId: 'income:bonus' },
  { id: 'dining', title: 'Weekend Dinner', subtitle: 'Dining - Restaurants', account: 'Visa Infinite', amount: -86.4, dateLabel: 'Sep 25', type: 'expense' as CategoryType, date: new Date(2025, 8, 25), categoryId: 'dining' as CategoryKey, subcategoryId: 'dining:restaurant' },
  { id: 'insurance', title: 'Auto Insurance', subtitle: 'Insurance - Auto', account: 'RBC Account', amount: -220, dateLabel: 'Sep 24', type: 'expense' as CategoryType, date: new Date(2025, 8, 24), categoryId: 'insurance' as CategoryKey, subcategoryId: 'insurance:auto' },
  { id: 'freelance', title: 'Freelance Payout', subtitle: 'Income - Freelance', account: 'PayPal', amount: 780, dateLabel: 'Sep 22', type: 'income' as CategoryType, date: new Date(2025, 8, 22), categoryId: 'income' as CategoryKey, subcategoryId: 'income:freelance' },
  { id: 'gym', title: 'Gym Membership', subtitle: 'Health - Gym & Fitness', account: 'Amex Platinum', amount: -55, dateLabel: 'Sep 20', type: 'expense' as CategoryType, date: new Date(2025, 8, 20), categoryId: 'health' as CategoryKey, subcategoryId: 'health:gym' },
  { id: 'investment', title: 'ETF Dividend', subtitle: 'Income - Investments', account: 'Questrade', amount: 160.75, dateLabel: 'Sep 18', type: 'income' as CategoryType, date: new Date(2025, 8, 18), categoryId: 'income' as CategoryKey, subcategoryId: 'income:investments' },
  { id: 'streaming', title: 'Streaming Bundle', subtitle: 'Entertainment - Streaming', account: 'Visa Infinite', amount: -32.99, dateLabel: 'Sep 16', type: 'expense' as CategoryType, date: new Date(2025, 8, 16), categoryId: 'entertainment' as CategoryKey, subcategoryId: 'entertainment:streaming' },
  { id: 'utilities', title: 'Water & Trash', subtitle: 'Utilities - Waste Services', account: 'Hydro One', amount: -128.5, dateLabel: 'Sep 14', type: 'expense' as CategoryType, date: new Date(2025, 8, 14), categoryId: 'utilities' as CategoryKey, subcategoryId: 'utilities:waste' },
  { id: 'electricity', title: 'Electricity Bill', subtitle: 'Utilities - Electricity', account: 'RBC Account', amount: -120.5, dateLabel: 'Sep 12', type: 'expense' as CategoryType, date: new Date(2025, 8, 12), categoryId: 'utilities' as CategoryKey, subcategoryId: 'utilities:electricity' },
  { id: 'dinner', title: 'Client Dinner', subtitle: 'Dining - Restaurants', account: 'Visa Infinite', amount: -75.2, dateLabel: 'Sep 10', type: 'expense' as CategoryType, date: new Date(2025, 8, 10), categoryId: 'dining' as CategoryKey, subcategoryId: 'dining:restaurant' },
  { id: 'bonus2', title: 'Performance Bonus', subtitle: 'Income - Bonus', account: 'RBC Account', amount: 2500, dateLabel: 'Sep 08', type: 'income' as CategoryType, date: new Date(2025, 8, 8), categoryId: 'income' as CategoryKey, subcategoryId: 'income:bonus' },
  { id: 'shopping', title: 'Online Shopping', subtitle: 'Groceries - Household Supplies', account: 'Amex Platinum', amount: -150.99, dateLabel: 'Sep 06', type: 'expense' as CategoryType, date: new Date(2025, 8, 6), categoryId: 'groceries' as CategoryKey, subcategoryId: 'groceries:household' },
  { id: 'gas', title: 'Fuel Stop', subtitle: 'Transportation - Fuel', account: 'Mastercard', amount: -45.3, dateLabel: 'Sep 04', type: 'expense' as CategoryType, date: new Date(2025, 8, 4), categoryId: 'transportation' as CategoryKey, subcategoryId: 'transportation:fuel' },
  { id: 'investment2', title: 'Dividend Payout', subtitle: 'Income - Investments', account: 'Questrade', amount: 200.75, dateLabel: 'Sep 02', type: 'income' as CategoryType, date: new Date(2025, 8, 2), categoryId: 'income' as CategoryKey, subcategoryId: 'income:investments' },
  { id: 'pharmacy', title: 'Pharmacy', subtitle: 'Health - Pharmacy', account: 'Visa Infinite', amount: -32.45, dateLabel: 'Aug 30', type: 'expense' as CategoryType, date: new Date(2025, 7, 30), categoryId: 'health' as CategoryKey, subcategoryId: 'health:pharmacy' },
  { id: 'concert', title: 'Concert Tickets', subtitle: 'Entertainment - Concerts', account: 'Amex Platinum', amount: -85, dateLabel: 'Aug 28', type: 'expense' as CategoryType, date: new Date(2025, 7, 28), categoryId: 'entertainment' as CategoryKey, subcategoryId: 'entertainment:concerts' },
  { id: 'freelance2', title: 'App Contract', subtitle: 'Income - Freelance', account: 'PayPal', amount: 1800, dateLabel: 'Aug 26', type: 'income' as CategoryType, date: new Date(2025, 7, 26), categoryId: 'income' as CategoryKey, subcategoryId: 'income:freelance' },
  { id: 'insurance2', title: 'Life Insurance', subtitle: 'Insurance - Life', account: 'RBC Account', amount: -350, dateLabel: 'Aug 24', type: 'expense' as CategoryType, date: new Date(2025, 7, 24), categoryId: 'insurance' as CategoryKey, subcategoryId: 'insurance:life' },
  { id: 'lunch', title: 'Lunch Run', subtitle: 'Dining - Fast Food', account: 'Visa Infinite', amount: -12.99, dateLabel: 'Aug 22', type: 'expense' as CategoryType, date: new Date(2025, 7, 22), categoryId: 'dining' as CategoryKey, subcategoryId: 'dining:fast' },
  { id: 'coffee2', title: 'Morning Coffee', subtitle: 'Dining - Coffee Shops', account: 'Visa Infinite', amount: -6.5, dateLabel: 'Aug 20', type: 'expense' as CategoryType, date: new Date(2025, 7, 20), categoryId: 'dining' as CategoryKey, subcategoryId: 'dining:coffee' },
  { id: 'movie2', title: 'Movie Night', subtitle: 'Entertainment - Movies', account: 'Amex Platinum', amount: -30, dateLabel: 'Aug 18', type: 'expense' as CategoryType, date: new Date(2025, 7, 18), categoryId: 'entertainment' as CategoryKey, subcategoryId: 'entertainment:movies' },
];

export const mockBudgetCategories = [
  { id: 'shopping', label: 'Shopping', spent: 7000, limit: 20000 },
  { id: 'groceries', label: 'Groceries', spent: 5200, limit: 12000 },
  { id: 'entertainment', label: 'Entertainment', spent: 1800, limit: 6000 },
  { id: 'subscriptions', label: 'Subscriptions', spent: 1400, limit: 3000 },
];

export const mockInitialReminders = [
  { id: '1', title: 'Monthly Rent', amount: 25000, schedule: 'Repeats monthly · 05 Mar 10:00' },
  { id: '2', title: 'Netflix Subscription', amount: 649, schedule: 'Repeats monthly · 08 Mar 11:00' },
  { id: '3', title: 'Amazon Prime', amount: 1499, schedule: 'Repeats yearly · 20 Apr 13:30' },
];

export const mockAccounts = [
  { id: 'all', name: 'All Accounts' },
  { id: 'icici-bank', name: 'ICICI Bank' },
  { id: 'sbi-bank', name: 'SBI Bank' },
  { id: 'axis-card', name: 'Axis Card' },
  { id: 'icici-card', name: 'ICICI Card' },
  { id: 'paytm', name: 'Paytm' },
  { id: 'cash', name: 'Cash' },
];

export const mockTransactionsList = [
  { id: 't1', title: 'Amazon', subtitle: 'Shopping', amount: -1050, date: 'Oct 15, 2025' },
  { id: 't2', title: 'Salary', subtitle: 'Income', amount: 50000, date: 'Oct 01, 2025' },
  { id: 't3', title: 'Groceries', subtitle: 'Food & Drinks', amount: -890, date: 'Sep 28, 2025' },
  { id: 't4', title: 'Mutual Fund', subtitle: 'Investments', amount: -2500, date: 'Sep 20, 2025' },
  { id: 't5', title: 'Electricity', subtitle: 'Utilities', amount: -120, date: 'Sep 15, 2025' },
  { id: 't6', title: 'Dinner', subtitle: 'Dining', amount: -75, date: 'Sep 10, 2025' },
  { id: 't7', title: 'Bonus', subtitle: 'Income', amount: 2500, date: 'Sep 05, 2025' },
  { id: 't8', title: 'Gas', subtitle: 'Transportation', amount: -45, date: 'Aug 30, 2025' },
  { id: 't9', title: 'Pharmacy', subtitle: 'Health', amount: -32, date: 'Aug 25, 2025' },
  { id: 't10', title: 'Concert', subtitle: 'Entertainment', amount: -85, date: 'Aug 20, 2025' },
];

export const mockWeeklyAmounts: Record<'expense' | 'income', number[]> = {
  expense: [95, 120, 60, 85, 190, 70, 45],
  income: [210, 160, 120, 140, 260, 180, 140],
};

