import { BorderRadius, FontSizes, FontWeights, Spacing } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const logExpensesStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  keyboardWrapper: {
    flex: 1,
  },
  scrollContent: {
    // reduce top space between header and content by lowering top padding
    paddingTop: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    paddingBottom: 250, // Increased back to 250 for better keyboard space
    gap: Spacing.md,
  },
  summaryContainer: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  accountSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  accountLabel: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.semibold as any,
  },
  summaryAmounts: {
    gap: 4,
  },
  summaryLabel: {
    fontSize: FontSizes.sm,
    letterSpacing: 0.6,
    // textTransform: 'uppercase',
  },
  summaryTotal: {
    fontSize: FontSizes.huge,
    fontWeight: FontWeights.bold as any,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  accountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  accountText: {
    fontWeight: FontWeights.semibold as any,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  iconButton: {
    padding: Spacing.sm,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  topControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    flexWrap: 'wrap',
  },
  addListButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    alignSelf: 'flex-end',
  },
  templatesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    alignSelf: 'flex-end',
  },
  templatesBadge: {
    fontSize: FontSizes.xs,
    lineHeight: FontSizes.xs,
    marginLeft: Spacing.xs,
    alignSelf: 'flex-start',
    paddingTop: 2,
  },
  addListLabel: {
    fontWeight: FontWeights.semibold as any,
    fontSize: FontSizes.sm,
  },
  sectionCard: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.lg,
  },
  recordCard: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.md,
    position: 'relative',
  },
  fieldGroup: {
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  fieldLabel: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium as any,
    letterSpacing: 0.4,
  },
  iconTouchArea: {
    padding: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  noteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  noteMenuButton: {
    alignSelf: 'center',
    justifyContent: 'center',
  },
  // small touch area for stacked actions (edit/delete) in top-right
  stackedIconGroup: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallIconTouch: {
    padding: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  noteInput: {
    flex: 1,
    fontSize: FontSizes.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: 0,
  },
  amountLabel: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold as any,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.tiny,
    justifyContent: 'flex-end',
    height: 48,
  },
  currencySymbol: {
    fontSize: FontSizes.huge,
    fontWeight: FontWeights.bold as any,
    lineHeight: FontSizes.huge + 4,
    textAlignVertical: 'center',
  },
  amountInput: {
    flexGrow: 0,
    flexShrink: 1,
    fontSize: FontSizes.huge,
    fontWeight: FontWeights.bold as any,
    padding: 0,
    lineHeight: FontSizes.huge + 4,
    textAlignVertical: 'center',
    textAlign: 'right',
    minWidth: 0,
    height: 48,
  },
  amountCompactInput: {
    minWidth: 36,
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold as any,
    padding: 0,
    lineHeight: FontSizes.lg + 4,
    textAlignVertical: 'center',
    textAlign: 'right',
  },
  inputWrapper: {
    position: 'relative',
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: 0,
    minHeight: 64,
    justifyContent: 'center',
  },
  inputWrapperNoBorder: {
    position: 'relative',
    borderWidth: 0,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: 0,
    minHeight: 48,
    justifyContent: 'center',
  },
  // A variant of inputWrapper that allows its height to expand when contents wrap
  inputWrapperTall: {
    // keep same minHeight but allow more vertical padding and flex-start so chips
    // and other multi-line content can stack without overlapping the notched label
    paddingTop: Spacing.md,
    paddingVertical: Spacing.sm,
    paddingBottom: Spacing.sm,
    minHeight: 84,
    // zIndex should not force overlay; set to default stacking
    zIndex: 0,
    marginBottom: Spacing.md,
    justifyContent: 'flex-start',
    // Prevent the input from growing indefinitely when a user adds many labels
    // Allow more room for many labels; content should push layout instead
    maxHeight: 200,
  },
  notchedLabel: {
    position: 'absolute',
    top: -10,
    left: Spacing.md,
    paddingHorizontal: Spacing.xs,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium as any,
  },
  notchedInput: {
    paddingTop: Spacing.sm,
    fontSize: FontSizes.lg,
    height: 48,
    textAlignVertical: 'center',
  },
  batchSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.lg,
  },
  categoryText: {
    fontSize: FontSizes.xl, // Increased from lg (16) to xl (18) for better readability
    fontWeight: FontWeights.medium as any,
  },
  recordFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  categoryPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    paddingVertical: 0,
    paddingHorizontal: 0,
    gap: Spacing.md,
    height: 48,
  },
  categoryIconBadge: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTextWrapper: {
    flex: 1,
  },
  categoryLabel: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold as any,
  },
  categoryPillCompact: {
    minWidth: 48,
    maxWidth: 80,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    height: 48,
    justifyContent: 'center',
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.tiny,
    justifyContent: 'flex-end',
  },
  currencyTiny: {
    // Use the same font-size and lineHeight as the compact amount input so
    // the currency symbol aligns perfectly with the numeric text.
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.semibold as any,
    lineHeight: FontSizes.lg + 4,
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  // deleteButton and menuButton moved to stack inside noteRow. Keep old classes if used elsewhere but keep them neutral
  deleteButton: {
    padding: Spacing.sm,
  },
  menuButton: {
    padding: Spacing.xs,
  },
  categoryInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 56,
    paddingVertical: 0,
  },
  batchTotal: {
    fontSize: FontSizes.huge,
    fontWeight: FontWeights.bold as any,
    lineHeight: FontSizes.huge + 4,
    textAlignVertical: 'center',
  },
  dateTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginTop: Spacing.md,
  },
  datePartWrapper: {
    flex: 1,
    // Keep the border and add consistent padding so icons are not tight to the edge
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: 0,
  },
  dateTimeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    width: '100%',
    height: 48,
    paddingLeft: Spacing.sm,
  },
  dateTimeButtonOutlined: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingVertical: 0,
    paddingHorizontal: Spacing.sm,
  },
  dateTimeButtonInput: {
    borderWidth: 0,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  dateTimeText: {
    fontSize: FontSizes.md,
    fontWeight: FontWeights.medium as any,
  },
  pickerContainer: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginTop: -Spacing.md,
  },
  pickerDoneButton: {
    alignSelf: 'flex-end',
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  batchList: {
    gap: Spacing.md,
  },
  batchCard: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    gap: Spacing.md,
  },
  batchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  batchTitle: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.semibold as any,
  },
  removeButton: {
    padding: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  batchInputs: {
    flexDirection: 'row',
    gap: Spacing.md,
    flexWrap: 'wrap',
  },
  batchField: {
    flex: 1,
    minWidth: 140,
  },
  batchAmountInput: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  addRecordButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    alignSelf: 'center', // Changed from 'flex-end' to 'center'
  },
  addRecordText: {
    fontWeight: FontWeights.semibold as any,
  },
  savedSummary: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.sm,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.15)',
    padding: Spacing.lg,
    justifyContent: 'flex-end',
  },
  menuContainer: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    paddingVertical: Spacing.sm,
    gap: Spacing.md,
    marginBottom: Spacing.sm,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  menuLabel: {
    fontWeight: FontWeights.medium as any,
  },
  labelsContainer: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  labelsSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  labelSummaryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    
  },
  labelActionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
  },
  labelChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.tiny,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.md,
     borderWidth: 1,
  },
  labelText: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium as any,
  },
  removeLabelButton: {
    padding: Spacing.tiny,
  },
  addLabelButton: {
    position: 'absolute',
    right: Spacing.sm,
    top: '50%',
    transform: [{ translateY: -10 }],
  },
  sharedLabelInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
    marginTop: Spacing.sm,
  },
  sharedLabelInputContainer: {
    position: 'relative',
    flex: 1,
  },
  sharedLabelInput: {
    flex: 1,
    borderWidth: 0,
    borderTopLeftRadius: BorderRadius.md,
    borderBottomLeftRadius: BorderRadius.md,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingRight: 50, // Space for the icon
    fontSize: FontSizes.md,
  },
  sharedLabelIconButton: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: BorderRadius.md,
    borderBottomRightRadius: BorderRadius.md,
    backgroundColor: 'transparent', // Or tint if needed
  },
  labelsContainerInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flexWrap: 'nowrap',
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.sm,
  },
  labelsScrollArea: {
    // Lock to a single row height so the container does not expand vertically.
    maxHeight: 72,
    flex: 1,
    width: '100%',
  },
  labelsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  labelsScrollInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  addLabelButtonStatic: {
    minWidth: 56,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    marginLeft: Spacing.sm,
  },
  labelChipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    flexWrap: 'nowrap',
    flex: 1,
    marginTop: Spacing.sm,
    minHeight: 56,
  },
  labelsAddRow: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.sm,
  },
  addLabelButtonCentered: {
    minWidth: 96,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
  },
  
  addLabelButtonInline: {
    padding: Spacing.xs,
    marginLeft: Spacing.xs,
  },
  labelAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    gap: Spacing.xs,
    // subtle elevation/shadow for visual depth
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  labelAddButtonText: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold as any,
  },
  // Reusable input base style for consistent height/padding
  inputBase: {
    height: 48,
    justifyContent: 'center',
  },
  labelsInlineInput: {
    minWidth: 120,
    flex: 1,
    borderWidth: 0,
    paddingVertical: 6,
    paddingHorizontal: 6,
    fontSize: FontSizes.md,
    height: 48,
    alignSelf: 'center',
    textAlignVertical: 'center',
  },
});