import { BorderRadius, FontSizes, FontWeights, Spacing } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const logExpensesStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  keyboardWrapper: {
    flex: 1,
  },
  scrollContent: {
    // reduce top space between header and content by lowering top padding
    paddingTop: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    paddingBottom: 250, // Increased back to 250 for better keyboard space
    gap: Spacing.md,
  },
  summaryContainer: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  accountSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  accountLabel: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.semibold as any,
  },
  summaryAmounts: {
    gap: 4,
  },
  summaryLabel: {
    fontSize: FontSizes.sm,
    letterSpacing: 0.6,
    // textTransform: 'uppercase',
  },
  summaryTotal: {
    fontSize: FontSizes.huge,
    fontWeight: FontWeights.bold as any,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
  },
  accountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  accountText: {
    fontWeight: FontWeights.semibold as any,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  iconButton: {
    padding: Spacing.sm,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  topControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    flexWrap: 'wrap',
  },
  addListButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    alignSelf: 'flex-end',
  },
  templatesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    alignSelf: 'flex-end',
  },
  templatesBadge: {
    fontSize: FontSizes.xs,
    lineHeight: FontSizes.xs,
    marginLeft: Spacing.xs,
    alignSelf: 'flex-start',
    paddingTop: 2,
  },
  addListLabel: {
    fontWeight: FontWeights.semibold as any,
    fontSize: FontSizes.sm,
  },
  sectionCard: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.lg,
  },
  recordCard: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  fieldGroup: {
    gap: Spacing.xs,
  },
  fieldLabel: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium as any,
    letterSpacing: 0.4,
  },
  iconTouchArea: {
    padding: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  noteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  noteMenuButton: {
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  noteInput: {
    flex: 1,
    fontSize: FontSizes.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: 0,
  },
  amountLabel: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold as any,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.tiny,
    paddingTop: Spacing.sm,
    justifyContent: 'flex-end',
  },
  currencySymbol: {
    fontSize: FontSizes.massive,
    fontWeight: FontWeights.bold as any,
    lineHeight: FontSizes.massive + 4,
    textAlignVertical: 'center',
  },
  amountInput: {
    flexGrow: 0,
    flexShrink: 1,
    fontSize: FontSizes.massive,
    fontWeight: FontWeights.bold as any,
    padding: 0,
    lineHeight: FontSizes.massive + 4,
    textAlignVertical: 'center',
    textAlign: 'right',
    minWidth: 0,
  },
  amountCompactInput: {
    minWidth: 60,
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.bold as any,
    padding: 0,
    lineHeight: FontSizes.lg + 4,
    textAlignVertical: 'center',
    textAlign: 'right',
  },
  inputWrapper: {
    position: 'relative',
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  notchedLabel: {
    position: 'absolute',
    top: -10,
    left: Spacing.md,
    paddingHorizontal: Spacing.xs,
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium as any,
  },
  notchedInput: {
    paddingTop: Spacing.sm,
    fontSize: FontSizes.lg,
  },
  batchSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.lg,
  },
  categoryText: {
    fontSize: FontSizes.xl, // Increased from lg (16) to xl (18) for better readability
    fontWeight: FontWeights.medium as any,
  },
  recordFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  categoryPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    paddingVertical: 0,
    paddingHorizontal: 0,
    gap: Spacing.md,
    height: 48,
  },
  categoryIconBadge: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryTextWrapper: {
    flex: 1,
  },
  categoryLabel: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold as any,
  },
  amountField: {
    minWidth: 110,
    maxWidth: 140,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    height: 48,
    justifyContent: 'center',
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.tiny,
    justifyContent: 'flex-end',
  },
  currencyTiny: {
    fontSize: FontSizes.md,
    fontWeight: FontWeights.semibold as any,
    // Align to the larger compact amount line (FontSizes.lg) so the dollar sign
    // sits on the same baseline as the numeric input.
    lineHeight: FontSizes.lg + 4,
    textAlignVertical: 'center',
  },
  deleteButton: {
    padding: Spacing.sm,
  },
  categoryInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Spacing.sm,
  },
  batchTotal: {
    fontSize: FontSizes.huge,
    fontWeight: FontWeights.bold as any,
    lineHeight: FontSizes.huge + 4,
    textAlignVertical: 'center',
  },
  dateTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  dateTimeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    width: '100%',
  },
  dateTimeButtonOutlined: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  dateTimeButtonInput: {
    borderWidth: 0,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  dateTimeText: {
    fontSize: FontSizes.md,
    fontWeight: FontWeights.medium as any,
  },
  pickerContainer: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginTop: -Spacing.md,
  },
  pickerDoneButton: {
    alignSelf: 'flex-end',
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  batchList: {
    gap: Spacing.md,
  },
  batchCard: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    gap: Spacing.md,
  },
  batchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  batchTitle: {
    fontSize: FontSizes.lg,
    fontWeight: FontWeights.semibold as any,
  },
  removeButton: {
    padding: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  batchInputs: {
    flexDirection: 'row',
    gap: Spacing.md,
    flexWrap: 'wrap',
  },
  batchField: {
    flex: 1,
    minWidth: 140,
  },
  batchAmountInput: {
    borderWidth: 1,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  addRecordButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    alignSelf: 'center', // Changed from 'flex-end' to 'center'
  },
  addRecordText: {
    fontWeight: FontWeights.semibold as any,
  },
  savedSummary: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    gap: Spacing.sm,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.15)',
    padding: Spacing.lg,
    justifyContent: 'flex-end',
  },
  menuContainer: {
    borderWidth: 1,
    borderRadius: BorderRadius.xl,
    paddingVertical: Spacing.sm,
    gap: Spacing.xs,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  menuLabel: {
    fontWeight: FontWeights.medium as any,
  },
  labelsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  labelsSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  labelSummaryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
  },
  labelActionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
  },
  labelChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.tiny,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
  },
  labelText: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.medium as any,
  },
  removeLabelButton: {
    padding: Spacing.tiny,
  },
  addLabelButton: {
    position: 'absolute',
    right: Spacing.sm,
    top: '50%',
    transform: [{ translateY: -10 }],
  },
  sharedLabelInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  sharedLabelInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    fontSize: FontSizes.md,
  },
  sharedLabelAction: {
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  labelsContainerInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flexWrap: 'wrap',
    paddingTop: Spacing.sm,
  },
  labelChipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    flexWrap: 'wrap',
    flex: 1,
  },
  
  addLabelButtonInline: {
    padding: Spacing.xs,
    marginLeft: Spacing.xs,
  },
  labelAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    gap: Spacing.xs,
    // subtle elevation/shadow for visual depth
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  labelAddButtonText: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold as any,
  },
  labelsInlineInput: {
    minWidth: 120,
    borderWidth: 0,
    paddingVertical: 6,
    paddingHorizontal: 6,
    fontSize: FontSizes.md,
    height: 36,
  },
});